name: Unpack ZIP automatically

on:
  push:
    branches: [ "principal" ]

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Extraire le ZIP
        run: |
          unzip -o "*.zip" -d extrait

      - name: Copier les fichiers extraits à la racine
        run: |
          cp -r extrait/* .

      - name: Supprimer le dossier extrait
        run: |
          rm -rf extrait
