name: Unpack ZIP automatically

on:
  push:
    branches: [ "principal" ]

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Extraire le ZIP
        run: |
          unzip -o "*.zip" -d extracted || echo "No ZIP found"

      - name: Copier les fichiers extraits
        run: |
          cp -r extracted/* .

      - name: Supprimer le ZIP et les dossiers temporaires
        run: |
          rm -rf extracted
          rm -f *.zip

      - name: Commit des fichiers
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit -m "Décompression automatique" || echo "Rien à valider"

      - name: Pousser les modifications
        run: |
          git push
